{% set name = "bitarray" %}
{% set version = "0.8.2" %}
{% set sha256 = "94a1747208b7ef1debfd469657f2d4b74446e170ba735927207a525602ebf0cc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Note extra .1 in filename
  fn: {{ name }}-{{ version }}.1.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.1.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install

requirements:
  host:
    - python

  build:
    - {{ compiler('c') }}

  run:
    - python

test:
  imports:
    - bitarray

about:
  home: https://github.com/ilanschnell/bitarray
  license: PSF
  summary: 'efficient arrays of booleans -- C extension'
  description: |
    Bitarray provides an object type which efficiently represents an array of
    booleans. Bitarrays are sequence types that behave very similarly
    to usual lists. All functionality is implemented in C.
  doc_url: https://pypi.python.org/pypi/bitarray/0.8.1
  doc_source_url: https://github.com/ilanschnell/bitarray/blob/master/README.rst
  dev_url: https://github.com/ilanschnell/bitarray

extra:
  recipe-maintainers:
    - nehaljwani
