{% set name = "bitarray" %}
{% set version = "3.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3eae38daffd77c9621ae80c16932eea3fb3a4af141fb7cc724d4ad93eff9210d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools >=42.0.0
  run:
    - python

test:
  imports:
    - bitarray
    - bitarray._bitarray
    - bitarray._util
    - bitarray.test_bitarray
    - bitarray.util
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --pyargs bitarray
  requires:
    - pip
    - pytest

about:
  home: https://github.com/ilanschnell/bitarray
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  summary: efficient arrays of booleans -- C extension
  description: |
    Bitarray provides an object type which efficiently represents an array of
    booleans. Bitarrays are sequence types that behave very similarly
    to usual lists. All functionality is implemented in C.
  doc_url: https://pypi.org/pypi/bitarray
  dev_url: https://github.com/ilanschnell/bitarray

extra:
  recipe-maintainers:
    - nehaljwani
