{% set name = "bitarray" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b2783d74247abb2669f581a001ecaa747e4b2ff9440762dbb499ed69b83e321e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - bitarray

about:
  home: https://github.com/ilanschnell/bitarray
  license: PSF
  # https://github.com/ilanschnell/bitarray/issues
  # license_file: LICENSE
  summary: 'efficient arrays of booleans -- C extension'
  description: |
    Bitarray provides an object type which efficiently represents an array of
    booleans. Bitarrays are sequence types that behave very similarly
    to usual lists. All functionality is implemented in C.
  doc_url: https://pypi.python.org/pypi/bitarray/0.8.1
  doc_source_url: https://github.com/ilanschnell/bitarray/blob/master/README.rst
  dev_url: https://github.com/ilanschnell/bitarray

extra:
  recipe-maintainers:
    - nehaljwani
