travis:
  secure:
    BINSTAR_TOKEN: f/JC5fPCbFvXCM6gduVdXYvYNoyApT4zI9ZEip6wNmRd/WdQxRcbUVMdXlp6yWSBYlk/bTQz28Q/taJjz6zjm4QcelzuDXljuhbxUaeuJle1Av8ej2Y8Jlv7wa3APASF0leJc9AF9K2oaspV73fIqflL3uPm9GaJ+HgszvrAX5Eov1FlHtRLPAVRl5hjr0HqYi9Q3fVQcJqwtpfoyof9Qn8xQlZN68qgjNsmiAlNBFhH1c+sDWsT0lImOEoQoahi1K0zr3ucbNzhIXRdxUVR8KeA3puORAvpPGFuFGHr62zBYC5um+avKIfxZB2WhC60CY8bKtfCtOIdosv5qbdtd7ygKQS2Yt2gtoGocHJWf2qFIPHsFQXnnuQA1nMsyH9fKmaAlskRBoJ7CFR+4D7ZH+AwD1GIY4BSS7y/iPRPLxS03G9y1iw0KncFZm1KUIfeT66dj0WtIvXU1lgeqLY03LtEGBvbL7YPglkYX4Tn3nNhmBUv2kFfdhcRjm/kKeTfo5C8Ulzzl4htGRBRqQtTUkjwZXgsBEO/HhpE1fN3mOgG77yfv06VCFjd7Di0j8VGwWvambrXQf1Dt/5n8E6YhXou+AxJ0CJoh4BD1huU9jqWWQjvFND615p6pEaBB9byvBY74gPOUEdsjAttzBOL6BJEwoOHcp03KKinYXziO/I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
