travis:
  secure:
    BINSTAR_TOKEN: X2UeFW8U/OisvVf7wUdeTwXijIScY4gDgzyut5x+L0NOwPVadNM+XIDqdBsOoQQSrUnnWqozXjl3kbUN5JxQKbP12dC+kTwhQf7wRJRcWJKqFACpJVV1uyJTCo8tjcErbLPkLWFYcKE6idZBwTNGT8PwDxCXsH2OVo3l9ZuvNUk8l/+5xPBHYaxQKG45Am8O2Ex9E58mGBfPiUfweuejhJ9jqlF1d1eWBwR7FQXz5UBKLsGNrdd5SkLbBlhumAARwJAllJc2E97rJqyJ5j2RThAKvUcBBALKGB2rXdoNO/OlBzTpDBYTQYxSWdX045azv7KopsbFCp0nDq0vSiQynG9AW5K8GHJaa9Fk7OSqNj7VkDAeAzvMLQAyu7ZnymQxo7lhvoXZvawjQuub0d8J+iQk9pP55eaTEYgWBJ9EQnNCBiD+fbFef9cwvqrHi/6lqc2JG8xXGf8uGNveG1BJVoAQAExmks2hfmZivEnPVUZ44kciVVpIHpj9eLYcIeAbm5TB1fNlpN6B9EpHsRFyFnTTvIRRfpmN1LAtuduTknKYzuPS2PVwirD5PfhRCpQIhPDyxg4Xw8f5yPEhFiw/wD2dVLNqbfqLSSOYEmBQjA2jnCHLBvhuXRX4oKF3lffUNPrK6Bj6tgmls0di//Enttjkp21vxSzK4tiXU7DeDas=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
