travis:
  secure:
    BINSTAR_TOKEN: i81MoZNEsmVOtP20bjWL20nVoWnKo/tQK+mTM+U18Tl9X6NsaY6ujGOHdAw+N2oUUceJ8HbFhJ/WBN08RL0WU7aCbncCEG3k4PhALn7okCJCZ5qSwU0NZl/pOtkNjlo6LLQO5BmEl29Owy3j0idbDyKkvTVHlB/mIWPCD89OSSXvX35Jb2tnsVp4tR3097A9lOaqnGlkY7E17ieYk5/7OjZr5Q+AS6TbneOfRBZ5PbtyNBIeCmYn9420XVXC+gxwImU/TbOrj4RHUL4RYcYsjQn0pZtSR4h43iopcfNlLpBN+BIE3c9KWZYL73T+6iSU4XUtMeThwZx47Q2yeBtQfpA3AYx7wQ4KU/3RZjOt6B8Aqm75UZNhJN+9epW9X97FC1Ok0lrZe7upMMZ63n5lo6FwBaIneS+lxqDgT/25BIcssbcMLs6FXpda0oWabCqq4LAUJeIlB5Op+Qg9qQPXuKYkW+9EWacqKtep7TyLf+dQOQZX9F11z69tDXqDdxmilSbXXCSbEke04Qx45vxzvELn+oD9e6LK89F7aTgXpTMwVwQiLqybFMlSn91XuooAGv1yFNnnXSuIjbmNnaogtglFyeuJ175Hw2BVVW938nuYJ8HZB1sVYfppv3P8o62YvC7vsVNXuJrE0b4KhXxlaolduiPGZyGCvSo/u23KuQI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
