travis:
  secure:
    BINSTAR_TOKEN: c/OypJi4ms0XmiF2vISRr350rFeRzyOSALsF5XMMiJA99mB9bbA34plO92mxgaBcTCED78KZzoOIzhXNI64z798bZpk33Yf5SK0E7nbBg1JlzG9kd7NfDh9d6NVJN8H+yn0/+hBTNBB4J/Vgs2MykMtgGOU1CNusNOF6HZt0nTrEu7NnoCRUZTeG1iB4SEhx7UWrO18kcdsuTRFBR3qiC2skwjQYl/g4eT16Nvh4CpNvyMqQGUObqVmI5UoY1oEcTgt11hP/40IeD7+D7voExpCrfpdy30hJO6tQHfJsyxGMO2YibGKVKcZXy8VvEuDWxEPcKjkboXYcvHm0eMP7qegPRnOh1Jps20pJJuN5ZEiMvaqN+FyFcrT5tI2cGMOmse5j2GOS83fKkyMa5yFJEsc7ZXfv0kUyWMAzD9zyiZJsjhbdz9QWcjDRdFOowMP1fOg1xKUTIFbZiHm1GfgT64zd3V9S8xEDhw8fXVkinW0WOKROsbL5CD4pT6fK29fhO/gepD35NAkts1h6obfJfKDY6+8/7k9KZF8bS9I1iylH6vM2BH0AG+vrJYOBJDUV5NsVxOs0G99cV/CRLwh+AEJR0WzmDi1eMv9ykrfhVQuT/UEYJI8ZjGf2SZB0WnifKmRgkEDC/BoDgyeJIQAyneu+CyfWVU9ieAUelA3GYR0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
